/**
 * ESLint Flat Configuration
 * Using Airbnb Style Guide + Next.js + TypeScript + Prettier
 */

import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "dist/**",
      "build/**",
      "*.config.js",
      "*.config.ts",
      "*.config.mjs",
      "next-env.d.ts", // Auto-generated by Next.js
    ],
  },
  // Airbnb style guide (the gold standard for React/TypeScript)
  ...compat.extends(
    "airbnb",
    "airbnb-typescript",
    "airbnb/hooks",
    "next/core-web-vitals",
    "next/typescript",
    "prettier" // Must be last to disable conflicting rules
  ),
  {
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
      },
    },
  },
  {
    rules: {
      // Adjust Airbnb rules for modern React/Next.js
      "react/react-in-jsx-scope": "off", // Not needed in Next.js
      "react/function-component-definition": [
        "error",
        {
          namedComponents: "function-declaration",
          unnamedComponents: "arrow-function",
        },
      ],
      "import/prefer-default-export": "off", // Named exports are fine
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "react/require-default-props": "off", // Not needed with TypeScript
      "react/jsx-props-no-spreading": "off", // Common pattern in Next.js/shadcn

      // Prisma-specific patterns
      "no-underscore-dangle": [
        "error",
        {
          allow: ["_count", "_sum", "_avg", "_min", "_max"], // Prisma aggregation fields
        },
      ],

      // Accessibility - relax some rules (can tighten later during a11y audit)
      "jsx-a11y/label-has-associated-control": [
        "error",
        {
          assert: "either", // Either htmlFor or nested control is fine
        },
      ],
      "jsx-a11y/no-autofocus": "warn", // Warn instead of error

      // Developer experience
      "no-console": [
        "warn",
        { allow: ["warn", "error"] }, // console.log is warned, warn/error allowed
      ],
      "react/no-unescaped-entities": "off", // Prettier handles this, quotes are fine in JSX
    },
  },
  // Overrides for scripts and utilities
  {
    files: ["scripts/**/*", "prisma/seed.ts"],
    rules: {
      "no-console": "off", // Console allowed in scripts
      "no-restricted-syntax": "off", // for-of loops are fine in scripts
      "no-await-in-loop": "off", // Sequential operations are fine in seed scripts
    },
  },
];

export default eslintConfig;
